export enum ForArtistNavigationGroups {
    DASHBOARD = 'FOR_ARTIST_NAVIGATION.DASHBOARD',
    RELEASES = 'FOR_ARTIST_NAVIGATION.RELEASES.BASE',
    ANALYTICS = 'FOR_ARTIST_NAVIGATION.ANALYTICS',
    SETTINGS = 'FOR_ARTIST_NAVIGATION.SETTINGS',
}
