import { Component, effect, Input, OnDestroy, OnInit } from '@angular/core';
import { ListEntitiesFacade } from '@common/facades/list-entities.facade';
import { FollowService } from '@common/services/follow-service';
import { TranslatePipe } from '@ngx-translate/core';
import { map, Observable, Subject } from 'rxjs';
import { Following } from './models/following';
import { FollowType } from '@common/layout/components/librarybar/enums/follow-type-enum';
import { UserStateService } from '@common/services/user-state.service';
import { AsyncPipe } from '@angular/common';

@Component({
    selector: 'action-follow-button',
    templateUrl: './follow-button.component.html',
    styleUrl: './follow-button.component.scss',
    imports: [TranslatePipe, AsyncPipe],
})
export class FollowButtonComponent
    extends ListEntitiesFacade<Following>
    implements OnDestroy, OnInit
{
    private readonly destroy$ = new Subject<void>();

    @Input() followeeId: string | undefined | null = null;
    @Input() type: FollowType = null!;
    isFollowed$!: Observable<boolean>;

    constructor(
        private readonly followService: FollowService,
        private readonly userStateService: UserStateService,
    ) {
        super(followService);
    }

    ngOnInit(): void {
        this.isFollowed$ = this.followService.onEntitiesChanged$.pipe(
            map((follows) => follows.some((follow) => follow.id === this.followeeId)),
        );

        this.followService.loadLocalUserFollows();
    }

    ngOnDestroy(): void {
        this.destroy$.next();
        this.destroy$.complete();
    }

    follow(): void {
        if (
            this.followeeId === null ||
            this.followeeId === undefined ||
            this.type === null ||
            this.type === undefined
        ) {
            return;
        }

        const entity: Following = {
            id: '', // This should be generated by the backend, so we can leave it empty here
            followerId: this.userStateService.value()?.id!,
            followeeId: this.followeeId,
            type: this.type,
        };

        this.followService.follow(entity);
    }

    unfollow(): void {
        if (
            this.followeeId === null ||
            this.followeeId === undefined ||
            this.type === null ||
            this.type === undefined
        ) {
            return;
        }

        this.followService.unfollow(this.followeeId);
    }
}
